### ISSUE TITLE
Status messages to be shown in UI

### ISSUE THREAD

**Issue by tuahinde** [CSCfi/DataCopierCore#1]
In order to keep the user informed about the progress of the data copier work , the following status messages are needed:
- received
- started
- progressing (for example: xx% of 100% or xx TB of yy TB or xx files of yy files)
- completed

Välitallennus tarvitaan: laitetaan kello ajamaan tallennusta. Timer to check more frequently in the beginning of the copy job? 

In the end, the UI to decide how frequently the API is polled.

**Comment by jarve** [comment]
Järjestelmä toimii ja tilanne päivittyy kantaan kopioinnin aikana:
Status 0 on kopiointi onnistuneesti valmis.
Status 1 tarkoittaa esim IDAn huoltokatkoa, pysyvä lopetus epäonnistuneena.
Status 11 kopionti käynnissä.
