### ISSUE TITLE
Email message about completed copy work

### ISSUE THREAD

**Issue by tuahinde** [CSCfi/DataCopierCore#2]
Since a copy work can last longer than the user keeps the UI session open, it would be convenient if an email was sent to the user when copy work is completed. 

Default in API that email is sent, but user can opt-out. 

User's email adress information to be found in IdM. To be fetched when copy job is ended and is not saved in Data Copier. Technically a LDAP-query with dedicated IdM user account. Engine to send query, LDAP to be opened. Solution to be discussed with IdM/Juha Nyholm.

**Comment by jarve** [comment]
Jos pyynnössä on {
    "requester": "tunnus",
    "email": true,...
tunnus saa yksinkertaisen sähköpostin työn valmistuttua esim:
Subject: | Tiedostokopiointisi webdav:sta Onnistui
Your file copy to s3 succeeded in 72.0s.
