### ISSUE TITLE
Status of the copy work to be shown when next UI session is opened

### ISSUE THREAD

**Issue by tuahinde** [CSCfi/DataCopierCore#3]
Since a copy work can last longer than the user keeps the UI session open, it would be convenient if the status of the copy work that where active when the session was closed, could be shown in the UI when next session is opened.

**Comment by jarve** [comment]
The data is available via status query` https://dc-core.rahtiapp.fi/v1/status/804`
The response is like
`{"copyid":804,"requester":"censored","email":true,"source":null,"destination":null,"status":0,"MB":10,"nofiles":1000,"wallclock":72.0}`
