### ISSUE TITLE
Create an API for status requests

### ISSUE THREAD

**Issue by tuahinde** [CSCfi/DataCopierCore#5]
User information to be added to status message.

UI asks which sessions a particular user have created during the last 30 days. API shows their statuses.

**Comment by jarve** [comment]
API is GET request like ` https://dc-core.rahtiapp.fi/v1/status/804`
The number is return value of the original POST request.
The response is like `{"copyid":804,"requester":"censored","email":true,"source":null,"destination":null,"status":0,"MB":10,"nofiles":1000,"wallclock":72.0}`
